### PR TITLE
[WIP] Dockerfile builder trial

### PR DESCRIPTION
**Pull request by MarckK**

### CODE REVIEW

**Comment by MarckK** [comment]
Start of refactoring out common commands in the Dockerfiles. 

Docker agent will fail.

**Comment by slide** [comment]
I think the alpine image is used on ci.j.io, we'll need to make sure an update any jobs that use it if it will no longer be published. We'll need to do it in general if the images are published to a different repo than they are now.

**Comment by dduportal** [comment]
@slide  Good point! Do you mind to also mention this in #23 as it is also removing the "alpine-root" image?

=> When updating the image reference for the `jenkins/jnlp-agent-alpine` image in `*jenkins.io` there will be only these cases:

* By default we can switch the reference to `jenkins/inbound-agent:alpine` (as the alpine image here inherits from this image and "only" set the default USER as root
* If the reference is in another `Dockerfile`, we'll have to add the `USER root` before any operation (and eventually the `USER jenkins` after)
* If the jobs using this container are failing because no rights to run an `apk add` command, then we'll have to determine what is expected and build custom images to address this use case

Sounds good?

**Comment by olblak** [comment]
> I think the alpine image is used on ci.j.io, we'll need to make sure an update any jobs that use it if it will no longer be published. We'll need to do it in general if the images are published to a different repo than they are now.

The alpine version is definitely defined in ci.j.io configuration but I couldn't find a place where it's used.
I quick search on show nothing neither
* https://github.com/search?q=org%3Ajenkins-infra+jenkins%2Fjnlp-agent-alpine&type=issues
* https://github.com/search?q=org%3Ajenkinsci+jenkins%2Fjnlp-agent-alpine&type=issues

**Comment by dduportal** [comment]
Closing this PR as the jenkins-infra moved its images to its own repository.

**Pull request closed without merging**
